; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "simple_load"
#define MyAppVersion GetEnv("APP_VERSION")
#define MyAppPublisher "gulei"
#define MyAppExeName "simple_load.exe"
#define MyAppURL RemoveBackslash(SourcePath)
#define MyAppProtocol "tmb-app"  ; �����Զ���Э������

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{69E2CE32-D066-476F-9870-949269F10FC7}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; �汾��Ϣ
VersionInfoVersion={#MyAppVersion}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Setup
VersionInfoTextVersion={#MyAppVersion}
VersionInfoCopyright=Copyright (C) {#MyAppPublisher}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={#MyAppURL}\software
OutputBaseFilename={#MyAppName}-{#MyAppVersion}
SetupIconFile={#MyAppURL}\static\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Nuitka standalone 输出为扁平目录（exe 与依赖 DLL/数据同级），递归复制即可
Source: "{#MyAppURL}\output\{#MyAppName}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; ע���Զ���URLЭ��
Root: HKCR; Subkey: "{#MyAppProtocol}"; ValueType: string; ValueName: ""; ValueData: "URL:TMB Application Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: "{#MyAppProtocol}"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCR; Subkey: "{#MyAppProtocol}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCR; Subkey: "{#MyAppProtocol}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

; ����ж��ʱ����ע�����
[UninstallDelete]
Type: files; Name: "{app}\*.*"
Type: filesandordirs; Name: "{app}"

[UninstallRun]
; ж��ʱ�����Զ���URLЭ��ע�����
Filename: "reg"; Parameters: "delete ""HKCR\{#MyAppProtocol}"" /f"; RunOnceId: "DelUrlProtocol"; Flags: runhidden